Show the url of localhost when `npm start`
erlliam/unnamed pull request #1
Opened 2021-10-21 00:50 UTC by JanPoonthong

2021-11-03 05:02 UTC, JanPoonthong commented
Fixed on commit: 3b05fb8246679858040d9545e624ed4e9106e345

2021-11-03 15:03 UTC, erlliam requested changes

2021-11-03 15:03 UTC, erlliam commented on .gitignore
> +unnamed.db
We shouldn't modify the `.gitignore`. Refer to my first comment. The example config in the README should be updated to contain reasonable defaults (directories/database inside of the project directory and the `.gitignore` would be updated to ignore these defaults). These changes belong in a different pull request.

2021-11-03 15:25 UTC, JanPoonthong commented on .gitignore
> +unnamed.db
Fix

2021-11-04 03:23 UTC, JanPoonthong commented on src/server.js
> +const server = app.listen(0, () => {
Fix in commit: 6b56188

2021-11-04 18:34 UTC, erlliam commented on src/server.js
> +  console.log(`Listening on port -> http://localhost:${port}`);
I'm thinking we should just say `Listening at ->` instead of `Listening on port ->`.

2021-11-05 09:39 UTC, JanPoonthong commented on src/server.js
> +  console.log(`Listening on port -> http://localhost:${port}`);
Fix on commit:cf1ca08

2021-11-05 17:05 UTC, erlliam approved these changes

2021-11-06 03:24 UTC, JanPoonthong commented
Yeah, ready for merge

2021-11-06 05:13 UTC, merged